# Generated by Django 2.0 on 2018-02-01 23:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Data',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('o3', models.CharField(max_length=10)),
                ('no2', models.CharField(max_length=10)),
                ('so2', models.CharField(max_length=10)),
                ('pm25', models.CharField(max_length=10)),
                ('pm10', models.CharField(max_length=10)),
                ('time', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Site',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Site name')),
                ('code', models.CharField(max_length=10, unique=True, verbose_name='Site code')),
                ('region', models.CharField(help_text='e.g. east-anglia', max_length=100, verbose_name='UK region')),
                ('environ', models.CharField(help_text='e.g. urban-traffic', max_length=100, verbose_name='Environment type')),
                ('url', models.URLField(help_text='URL link to DEFRA webpage', max_length=1000, verbose_name='DEFRA website link')),
                ('map_url', models.URLField(max_length=1000, verbose_name='Google maps url')),
                ('latitude', models.CharField(max_length=50)),
                ('longitude', models.CharField(max_length=50)),
            ],
            options={
                'ordering': ('name',),
            },
        ),
        migrations.AddField(
            model_name='data',
            name='site',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Site'),
        ),
    ]
