# Generated by Django 2.0 on 2018-01-16 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='site',
            name='code',
            field=models.CharField(max_length=10, unique=True, verbose_name='Site code'),
        ),
        migrations.AlterField(
            model_name='site',
            name='name',
            field=models.CharField(max_length=100, unique=True, verbose_name='Site name'),
        ),
    ]
